name: remote ssh command
on: [push]
jobs:
 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: ${{ secrets.SFTP_PORT }}
        script: whoami
 
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SFTP_PORT }}
        script: whoami
 
    - name: multiple command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SFTP_PORT }}
        script: |
          whoami
          ls -al
 
    # - name: stop script if command error
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.KEY }}
    #     port: ${{ secrets.PORT }}
    #     script_stop: true
    #     script: "mkdir abc/def,ls -al"
 
    - name: pass environment
      uses: appleboy/ssh-action@master
      env:
        FOO: "BAR"
      with:
        host: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        key: ${{ secrets.SSH_TEST_KEY }}
        port: ${{ secrets.SFTP_PORT }}
        envs: FOO
        script: |
          echo "I am $FOO"
          echo "I am $BAR"