name: Deploy to SFTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v3.1.2
        with:
          ftp-server: ${{ secrets.SFTP_SERVER }}
          ftp-username: ${{ secrets.SFTP_USERNAME }}
          ftp-password: ${{ secrets.SFTP_PASSWORD }}
          local-dir: ./
          git-ftp-args: --insecure --remote-root /chemin/vers/ton/dossier/
